FROM nvidia/cuda:10.2-base-ubuntu18.04
MAINTAINER Jerrick Liu

LABEL description="Running MineRL with Stable baselines"

WORKDIR /current/project/path

RUN apt-get update && apt-get install -y \
cmake \
libopenmpi-dev \
python3-dev \
zlib1g-dev \
xvfb \
python3 \
python3-pip \
python3-setuptools \
python3-venv \
&& \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

RUN pip3 install stable-baselines[mpi]
RUN pip3 install --upgrade minerl

COPY project_dir/ ./project_dir
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY jdk1.8.0_261/ ./jdk1.8.0_261

ENV JAVA_HOME="/path/to/your/java/installation/"



RUN python3 /path/to/your/script
