FROM nvidia/cuda:10.2-base-ubuntu18.04


MAINTAINER Jerrick Liu

LABEL description="Running MineRL headless"

WORKDIR /current/project/path/

RUN apt-get update && apt-get install -y \
cmake \
openjdk-8-jdk \
openssh-server \
libxrender-dev \
libopenmpi-dev \
zlib1g-dev \
x11-xserver-utils \
xvfb \
build-essential python3.6 python3.6-dev python3-pip python3.6-venv


# update pip
RUN python3.6 -m pip install pip --upgrade && \
        python3.6 -m pip install wheel

RUN pip3 install stable-baselines[mpi]
RUN pip3 install --upgrade minerl --user

COPY current/project/path/ ./project
COPY requirements.txt .
RUN pip3 install -r requirements.txt


CMD xvfb-run python3 /path/to/script




