FROM nvidia/cuda:10.2-base-ubuntu18.04
MAINTAINER Jerrick Liu

LABEL description="Practice docker image"

WORKDIR /home/jliu/Desktop/RL/baselines/general/chainerrl

RUN apt-get update && apt-get install -y \
cmake \
libopenmpi-dev \
python3-dev \
zlib1g-dev \
xvfb \
python3 \
python3-pip \
python3-setuptools \
python3-venv \
&& \
apt-get clean && \
rm -rf /var/lib/apt/lists/*

RUN pip3 install stable-baselines[mpi]
RUN pip3 install --upgrade minerl

COPY baselines/ ./baselines
COPY requirements.txt .
RUN pip3 install --no-cache-dir -r requirements.txt
COPY jdk1.8.0_261/ ./jdk1.8.0_261

ENV JAVA_HOME="/home/jliu/Desktop/RL/baselines/general/chainerrl/jdk1.8.0_261"



RUN xvfb-run python3 /home/jliu/Desktop/RL/baselines/general/chainerrl/baselines/mine.py
